version: '3.9'
services:

  dev:
    container_name: transactions_ms_dev
    image: transactions_ms_dev:0.0.3
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - default
    volumes:
      - .:/urs/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  prod:
    container_name: transactions_ms_prod
    image: transactions_ms_prod:0.0.3
    build: 
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - default
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped
  
networks:
  default:
    name: quick-bank-network
    external: true